// apps/vue/src/App.vue
<template>
  <p>First name: {{ firstName }}</p>
  <p>Last name:</p>
  <sinch-input
    :value="secondName"
    @change="secondName = $event.detail"
  ></sinch-input>
  <sinch-button value="Next" @click="onClick"></sinch-button>
</template>

<script lang="ts">
import "@saas/components/button";
import "@saas/components/input";
import "@saas/components/checkbox";

export default {
  methods: {
    onClick() {
      this.bus.postMessage({
        type: "SECOND_STEP_DONE",
        value: this.secondName,
      });
    },
  },
  props: {
    firstName: String,
  },
  data() {
    return {
      secondName: "Doe",
    };
  },
  mounted() {
    this.bus = new BroadcastChannel("TEST_CHANNEL");
  },

  unmounted() {
    this.bus.close();
  },
};
</script>

// apps/react-2/src/App.tsx
import { FC, useEffect, useRef, useState } from 'react'
import '@saas/components/button'
import '@saas/components/input'
import '@saas/components/checkbox'

export const App: FC<{}> = () => {
  const bus = useRef<BroadcastChannel>()
  const [value, setValue] = useState('John')

  const onClick = () => {
    bus.current?.postMessage({ type: 'FIRST_STEP_DONE', value })
  }

  useEffect(() => {
    bus.current = new BroadcastChannel('TEST_CHANNEL')

    return () => {
      bus.current?.close()
    }
  })

  return (
    <div>
      <p>First name:</p>
      <sinch-input value={value} onChange={setValue}></sinch-input>
      <sinch-button value="Next" onClick={onClick}></sinch-button>
    </div>
  )
}
