// apps/angular/src/app/app.component.ts
import { Component, Input } from '@angular/core'
import '@saas/components/button'
import '@saas/components/input'

@Component({
  selector: '#app',
  templateUrl: './app.component.html',
})

export class AppComponent {
  @Input() firstName!: string
  @Input() lastName!: string
  bus!: BroadcastChannel

  ngOnInit() {
    this.bus = new BroadcastChannel('TEST_CHANNEL')
  }

  ngOnDestroy() {
    this.bus.close()
  }

  handleOnClick() {
    this.bus.postMessage({ type: 'THIRD_STEP_DONE'})
  }
}

<p>first name: {{ firstName }}</p>
<p>last name: {{ lastName }}</p>
<sinch-button (click)="handleOnClick()" value="Done"></sinch-button>

// apps/react-2/src/App.tsx
import { FC, useEffect, useRef, useState } from 'react'
import '@saas/components/button'
import '@saas/components/input'
import '@saas/components/checkbox'

export const App: FC<{}> = () => {
  const bus = useRef<BroadcastChannel>()
  const [value, setValue] = useState('John')

  const onClick = () => {
    bus.current?.postMessage({ type: 'FIRST_STEP_DONE', value })
  }

  useEffect(() => {
    bus.current = new BroadcastChannel('TEST_CHANNEL')

    return () => {
      bus.current?.close()
    }
  })

  return (
    <div>
      <p>First name:</p>
      <sinch-input value={value} onChange={setValue}></sinch-input>
      <sinch-button value="Next" onClick={onClick}></sinch-button>
    </div>
  )
}
